#!/bin/sh
# -*-scheme-*-
exec guile -e "(@@ (guilescript) main)" -s "$0" "$@"
!#

;;; (guilescript) --- GuileScript.

;; Copyright (C) 2022 Aleix Conchillo Flaque <aconchillo@gmail.com>
;;
;; This file is part of GuileScript.
;;
;; GuileScript is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3 of the License, or
;; (at your option) any later version.
;;
;; GuileScript is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
;; General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GuileScript. If not, see https://www.gnu.org/licenses/.

;;; Commentary:

;; GuileScript CLI

;;; Code:

(define-module (guilescript)
  #:use-module (ice-9 match)
  #:use-module (language guilescript compile))

(define main
  (match-lambda
    ((_)
     (display "Usage: guilescript filename")
     (newline)
     (exit 1))
    ((_ filename) (display (compile-file filename)))))
